export default {
  dark: false,
  colors: {
    'background': '#F5F5F5',
    'on-background': '#333639',
    'surface': '#FFF',
    'on-surface': '#333639',
    'primary': '#1890FF',
    'on-primary': '#FFF',
    'success': '#18A058',
    'on-success': '#FFF',
    'warning': '#F0A020',
    'on-warning': '#FFF',
    'error': '#D03050',
    'on-error': '#FFF',
    'info': '#2080F0',
    'on-info': '#FFF',
  },
  variables: {
    'border-color': '#000',
    'border-opacity': 0.08,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'activated-opacity': 0.12,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'dragged-opacity': 0.08,
    'pressed-opacity': 0.16,
    'code-background-color': '#F4F4F8',
  },
}