export default {
  dark: false,
  colors: {
    background: '#FFF',
    surface: '#FFF',
    primary: '#1890FF',
    success: '#52C41A',
    warning: '#FAAD14',
    error: '#FF7875',
    info: '#2196F3',
  },
  variables: {
    'border-color': '#000',
    'border-opacity': 0.08,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'activated-opacity': 0.12,
    'idle-opacity': 0.04,
    'hover-opacity': 0.12,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'dragged-opacity': 0.08,
    'pressed-opacity': 0.16,
    'kbd-background-color': '#212529',
    'kbd-color': '#FFF',
    'code-background-color': '#C2C2C2',
  },
}