export default {
  defaultTheme: 'light',
  themes: {
    light: {
      dark: false,
      colors: {
        background: '#FFF',
        surface: '#FFF',
        primary: '#165DFF',
        secondary: '#F2F3F5',
        success: '#00B42A',
        warning: '#f0a020',
        error: '#F53F3F',
        info: '#2080F0',
      },
      variables: {
        'border-color': '#000',
        'border-opacity': 0.08,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'activated-opacity': 0.14,
        'idle-opacity': 0.04,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'dragged-opacity': 0.08,
        'pressed-opacity': 0.16,
      },
    },
    dark: {
      dark: true,
      colors: {
        background: '#101014',
        surface: '#18181C',
        primary: '#296DFF',
        secondary: '#27272A',
        success: '#00B42A',
        warning: '#FF7D00',
        error: '#F53F3F',
        info: '#2080F0',
      },
      variables: {
        'border-color': '#FFF',
        'border-opacity': 0.08,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'activated-opacity': 0.12,
        'idle-opacity': 0.10,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'dragged-opacity': 0.08,
        'pressed-opacity': 0.16,
      },
    },
  }
}