export default {
  defaultTheme: 'light',
  themes: {
    dark: {
      dark: true,
      colors: {
        background: '#101014',
        surface: '#18181C',
        primary: '#296DFF',
        secondary: '#27272A',
        success: '#00B42A',
        warning: '#FF7D00',
        error: '#F53F3F',
        info: '#2080F0',
      },
      variables: {
        'border-color': '#FFF',
        'border-opacity': 0.08,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'activated-opacity': 0.12,
        'idle-opacity': 0.10,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'dragged-opacity': 0.08,
        'pressed-opacity': 0.16,
        'code-background-color': '#2e2e30',
        'code-color': '#c1c1c1',
      },
    },
    light: {
      dark: false,
      colors: {
        background: '#FFF',
        surface: '#FFF',
        primary: '#165DFF',
        secondary: '#F2F3F5',
        success: '#00B42A',
        warning: '#f0a020',
        error: '#F53F3F',
        info: '#2080F0',
      },
      variables: {
        'border-color': '#000',
        'border-opacity': 0.08,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.60,
        'disabled-opacity': 0.38,
        'activated-opacity': 0.14,
        'idle-opacity': 0.04,
        'hover-opacity': 0.12,
        'focus-opacity': 0.12,
        'selected-opacity': 0.08,
        'dragged-opacity': 0.08,
        'pressed-opacity': 0.16,
        'code-background-color': '#f6f6f6',
        'code-color': '#2c3e50',
      },
    },
  },
  variations: {
    colors: [
      'primary',
      'secondary',
      'success',
      'warning',
      'error',
      'info',
    ],
    lighten: 4,
    darken: 4
  }
}